/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.javaweb.ch12.struts.action;

import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.javaweb.ch12.model.Operator;
import com.javaweb.ch12.service.IAdminOperator;



/** 
 * 功能:增加操作员
 */
public class AddOperatorAction extends BaseAction {
	/*
	 * Generated fields
	 */

	/** operatorName property */
	private String operatorName;

	/** operatorId property */
	private String operatorId;

	/** isAdmin property */
	private String isAdmin;

	/** operatorPwd property */
	private String operatorPwd;

	/** 
	 * Returns the operatorName.
	 * @return String
	 */
	public String getOperatorName() {
		return operatorName;
	}

	/** 
	 * Set the operatorName.
	 * @param operatorName The operatorName to set
	 */
	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	/** 
	 * Returns the operatorId.
	 * @return String
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/** 
	 * Set the operatorId.
	 * @param operatorId The operatorId to set
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/** 
	 * Returns the isAdmin.
	 * @return String
	 */
	public String getIsAdmin() {
		return isAdmin;
	}

	/** 
	 * Set the isAdmin.
	 * @param isAdmin The isAdmin to set
	 */
	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	/** 
	 * Returns the operatorPwd.
	 * @return String
	 */
	public String getOperatorPwd() {
		return operatorPwd;
	}

	/** 
	 * Set the operatorPwd.
	 * @param operatorPwd The operatorPwd to set
	 */
	public void setOperatorPwd(String operatorPwd) {
		this.operatorPwd = operatorPwd;
	}

	public String execute(){
		Operator operator=new Operator();
		operator.setIsAdmin(Integer.valueOf(isAdmin));
		operator.setOperatorId(Integer.valueOf(operatorId));
		operator.setOperatorName(operatorName);
		operator.setOperatorPwd(operatorPwd);
		//加载Spring配置文件，初始化IOC容器
		ClassPathXmlApplicationContext context=new ClassPathXmlApplicationContext("/applicationContext.xml");
		//从容器接管bean
		IAdminOperator admin=(IAdminOperator)context.getBean("adminservice");
		//调用业务层的方法判断是否是合法用户
		String message=admin.addOperator(operator);
		System.out.println(message);
		if(!message.equals("")){
			this.request().setAttribute("message", message);
			return SUCCESS;
		}else{
			return INPUT;
		}
	}
}