/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.javaweb.ch12.struts.action;

import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.javaweb.ch12.model.Customer;
import com.javaweb.ch12.model.Mobile;
import com.javaweb.ch12.model.User;
import com.javaweb.ch12.service.IOperator;



/** 
 * 功能:增加手机用户
 * 
 */
public class AddUserAction extends BaseAction {
	/** comLevel property */
	private String comLevel;

	/** mobile property */
	private String mobile;

	/** roamingStatus property */
	private String roamingStatus;

	/** 
	 * Returns the comLevel.
	 * @return String
	 */
	public String getComLevel() {
		return comLevel;
	}

	/** 
	 * Set the comLevel.
	 * @param comLevel The comLevel to set
	 */
	public void setComLevel(String comLevel) {
		this.comLevel = comLevel;
	}

	/** 
	 * Returns the mobile.
	 * @return String
	 */
	public String getMobile() {
		return mobile;
	}

	/** 
	 * Set the mobile.
	 * @param mobile The mobile to set
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/** 
	 * Returns the roamingStatus.
	 * @return String
	 */
	public String getRoamingStatus() {
		return roamingStatus;
	}

	/** 
	 * Set the roamingStatus.
	 * @param roamingStatus The roamingStatus to set
	 */
	public void setRoamingStatus(String roamingStatus) {
		this.roamingStatus = roamingStatus;
	}
	
	public String execute(){
		Customer customer=(Customer)this.session().getAttribute("customer");
		this.session().removeAttribute("customer");
		//加载Spring配置文件，初始化IOC容器
		ClassPathXmlApplicationContext context=new ClassPathXmlApplicationContext("/applicationContext.xml");
		//从容器接管bean
		IOperator dooperator=(IOperator)context.getBean("operatorservice");
		//调用业务层的方法判断手机号是否可用
		Mobile mobiles=dooperator.isMobileCanUse(mobile);
		String message="";
		if(mobiles!=null){//先判断手机号是否可用
			User user=new User();
			user.setComLevel(comLevel);
			user.setRoamingStatus(roamingStatus);
			user.setCustomer(customer);
			user.setMobile(mobiles);
			message=dooperator.addUser(user);//调用业务层的方法增加手机用户
			this.request().setAttribute("message", message);
			return SUCCESS;
		}else{
			message="添加用户失败!该手机号已被占用!";
			this.request().setAttribute("message", message);
			return INPUT;
		}
	}
}