/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.javaweb.ch12.struts.action;

import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.javaweb.ch12.service.IAdminOperator;


/** 
 * 功能:设置业务收费
 * 
 */
public class EditChargeRuleAction extends BaseAction {
	/*
	 * Generated fields
	 */

	/** rule property */
	private String rule;

	/** iterm property */
	private String iterm;

	/** 
	 * Returns the rule.
	 * @return String
	 */
	public String getRule() {
		return rule;
	}

	/** 
	 * Set the rule.
	 * @param rule The rule to set
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	/** 
	 * Returns the iterm.
	 * @return String
	 */
	public String getIterm() {
		return iterm;
	}

	/** 
	 * Set the iterm.
	 * @param iterm The iterm to set
	 */
	public void setIterm(String iterm) {
		this.iterm = iterm;
	}
	
	public String execute(){
		//得到页面传过来的收费细项,由于收费种类可能有多项,所以用数组
		String[] chargestr=this.request().getParameterValues("item");	
		//加载Spring配置文件，初始化IOC容器
		ClassPathXmlApplicationContext context=new ClassPathXmlApplicationContext("/applicationContext.xml");
		//从容器接管bean
		IAdminOperator admin=(IAdminOperator)context.getBean("adminservice");
		System.out.println("hello!");
		//调用业务层的方法设置业务收费
		String message=admin.editChargeRule(rule, chargestr);
		System.out.println(message);
		if(!message.equals("")){
			this.request().setAttribute("message", message);
			return SUCCESS;
		}
		else{
			return INPUT;
		}
	}
}