/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.javaweb.ch12.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.context.support.FileSystemXmlApplicationContext;

import com.javaweb.ch12.model.Operator;
import com.javaweb.ch12.service.ILogin;
import com.opensymphony.xwork2.ActionSupport;




/** 
 * 功能:用户登录
 * 
 */
public class LoginAction extends BaseAction {
	/*
	 * Generated fields
	 */

	/** password property */
	private String password;

	/** name property */
	private String name;
	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	public String execute(){
		//加载Spring配置文件，初始化IOC容器
		ClassPathXmlApplicationContext context=new ClassPathXmlApplicationContext("/applicationContext.xml");
		//从容器接管bean
		ILogin login=(ILogin)context.getBean("loginservice");
		//调用业务层的方法判断是否是合法用户
		Operator operator=login.isOperator(name, password);
		if(operator!=null){
			this.session().setAttribute("operator", operator);
			return SUCCESS;
		}else{
			return ERROR;
		}
	}
}